# -*- coding: utf-8 -*-
"""Image Compression of College.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJWxb3wTnQJ_0-aDyjuXjTUt5DuvPFLd
"""

import matplotlib.pyplot as plt

from skimage.io import imread

img = imread('Galgotias-university.png')

import matplotlib.pyplot as plt

plt.show()

plt.imshow(img)

plt.show()

img = img/225

img

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)

img.shape

img_format = img.reshape(389 * 700, 3)

img_format

kmeans.fit(img_format)

clusters = kmeans.predict(img_format)

clusters

kmeans.cluster_centers_

kmeans.cluster_centers_[[0,0]]

img_new = kmeans.cluster_centers_[clusters]

new_img = img_new.reshape(389, 700, 3)

plt.imshow(new_img)

plt.show()

input("Press Enter to exit...")




