# -*- coding: utf-8 -*-
"""Image Compression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXz3uKkqGajRfZRwXEbNXmuJU4izpK9n
"""

from skimage.io import imread

img = imread('college.png')

import matplotlib.pyplot as plt

plt.show()

plt.imshow(img)

plt.show()

img = img/225

img

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)

img.shape

img_format = img.reshape(900 * 1600, 4)

img_format

kmeans.fit(img_format)

clusters = kmeans.predict(img_format)

clusters

kmeans.cluster_centers_

kmeans.cluster_centers_[[0,0]]

img_new = kmeans.cluster_centers_[clusters]

new_img = img_new.reshape(900, 1600,4)

plt.imshow(new_img)

plt.show()

